version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version you are using
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the application..."
      - npm run build  # Replace this with your actual build command if necessary

artifacts:
  files:
    - '**/*'  # Include all files in the build artifacts
